// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQB6y240V5TI7btzQldRTyDi5KpYon_nA',
    appId: '1:73157383007:web:c894fc66fbe34ce6f35cea',
    messagingSenderId: '73157383007',
    projectId: 'newdemo-2de7c',
    authDomain: 'newdemo-2de7c.firebaseapp.com',
    storageBucket: 'newdemo-2de7c.appspot.com',
    measurementId: 'G-P1JEJMEPZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6JvkE4M3nAFM1w9OiEry9q4bNtQ3GU0',
    appId: '1:73157383007:android:ab8492d05ceb3779f35cea',
    messagingSenderId: '73157383007',
    projectId: 'newdemo-2de7c',
    storageBucket: 'newdemo-2de7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBFIFF0-NXpy1fzXEUiURZXzfFm08eUA',
    appId: '1:73157383007:ios:41e072ed7d20d0a6f35cea',
    messagingSenderId: '73157383007',
    projectId: 'newdemo-2de7c',
    storageBucket: 'newdemo-2de7c.appspot.com',
    iosBundleId: 'com.example.firestoreBsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBFIFF0-NXpy1fzXEUiURZXzfFm08eUA',
    appId: '1:73157383007:ios:4048f77873ce0deaf35cea',
    messagingSenderId: '73157383007',
    projectId: 'newdemo-2de7c',
    storageBucket: 'newdemo-2de7c.appspot.com',
    iosBundleId: 'com.example.firestoreBsp.RunnerTests',
  );
}
